export * from './Block'
export { default as SkeletonPage } from './SkeletonPage.astro'
export { default as BasicPage } from './BasicPage.astro'
export { default as AdminHidden } from './AdminHidden.astro'
export { default as HomePage } from './HomePage.astro'
export { default as EventPage } from './EventPage.astro'
export { default as OrganizationPage } from './OrganizationPage.astro'
export { default as ArticlesPage } from './ArticlesPage.astro'
export { default as ArticlePage } from './ArticlePage.astro'
export { default as AreasPage } from './AreasPage.astro'
export { default as AreaPage } from './AreaPage.astro'

// export { default as BlogLayout } from './BlogLayout.astro'
